<?php $subtitle = "Mobile Billing Solution boxPAY Announces 5 New Countries Added to Network";
include($_SERVER['DOCUMENT_ROOT'].'/includes/head.php');
include($_SERVER['DOCUMENT_ROOT'].'/includes/header.php')?>	
	
		
	<div class="row primary-row">	
  		
  		
  		
  		<section role="main">
  			
  			
  			<div class="row primary-container">
  				<div class="eight columns centered">
  
  					<h2>Mobile Billing Solution boxPAY Announces 5 New Countries Added to Network</h2>
  					
  					<h4>Company Offers Merchants Expanded Reach in EU; Monetizes New Customer Base for Web Merchants and Game Developers</h4>
  					
  					<p><strong>Dublin, Ireland; September 13, 2011</strong> – boxPAY Ltd., a provider of SMS-based mobile billing services to web merchants, announced additional service coverage in 3 new European Union countries, as well as two other additional countries. Denmark, Finland, and Poland were added to the worldwide mobile billing platform in the EU, and Israel and Turkey were also added to the boxPAY platform. This expands the reach of all boxPAY merchants to include mobile phone users with multiple carriers in all of these countries, creating an additional potential customer base of millions of people.</p>
  					
  					<p>boxPAY now provides merchants the ability to bill customers for virtual goods and services via their mobile phones in any of these 5 countries, in addition to 30 other countries already on the boxPAY platform. "A web-based merchant simply needs to sign-up on boxPAY.com, and can begin billing in the same day on the user-friendly, self-service platform. Customers only need their mobile phone to make a purchase, simply entering their number on a merchant website and confirming the transaction though an SMS message" said Kyle Hitchcox, Director of Strategic Partnerships. boxPAY merchants can take advantage of localized translations for each of the worldwide countries build into the platform, and all of the language and code necessary is auto-generated by boxPAY.</p>
  					
  					<p>The boxPAY platform is ideally suited for online games, virtual goods, social networks, classified sites, premium content, and many other e-businesses.</p>
  					
  					
  					<?php include($_SERVER['DOCUMENT_ROOT'].'/includes/about-blurb.php')?>
  					
  					  					
  					</div>
  				</div>
  				
  				
  				
  				
  				
  				
  				</div>
  				
  				
  				
  				
  		
  			
  		
  		</section>
  		
  		
  		
  		
  		<?php include($_SERVER['DOCUMENT_ROOT'].'/includes/sidebar.php')?>
		
	</div><!-- container -->
			
 
<?php include($_SERVER['DOCUMENT_ROOT'].'/includes/footer.php')?>